#!/bin/bash

# Regex to validate the type pattern
REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"

FILE=$(cat "$1") # File containing the commit message

if [[ $FILE =~ $REGEX ]]; then
    echo "✅ Commit message follows Conventional Commit standard"
    exit 0
else
    echo "❌ Commit message does not follow Conventional Commit standard"
    exit 1
fi
