apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: finance-${ENVIRONMENT}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  clusterIP: None
