version: '3.8'

services:
  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile
      args:
        - NGINX_BACKEND_API_REDIRECT=true
    platform: "linux/amd64"
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../.
      dockerfile: docker/backend/Dockerfile
    platform: "linux/amd64"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=${DATABASE_HOST-mariadb}
      - DATABASE_PORT=${DATABASE_PORT-3306}
      - DATABASE_NAME=${DATABASE_NAME-finance}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
    depends_on:
      - mariadb
