version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASS}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest  # no compatibility errors expected, so latest is fine
    platform: linux/amd64  # there is no linux/arm64v8 image
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
