name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  commit-message:
    name: Conventional Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Commit Messages
        run: |
          regex="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\(.*\\))?!?: .*))"
          commits=$(git log "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}" --format=%s)
          status=0
          while IFS= read -r msg; do
            if [[ ! $msg =~ $regex ]]; then
              echo "\u274c '$msg' does not follow Conventional Commit standard"
              status=1
            else
              echo "\u2705 '$msg' follows Conventional Commit standard"
            fi
          done <<< "$commits"
          exit $status

  backend-format-check:
    name: Backend Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check Formatting
        run: |
          cd backend
          chmod +x ./mvnw
          ./mvnw spotless:check

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Tests
        run: |
          cd backend
          chmod +x ./mvnw
          ./mvnw test

  frontend-checks:
    name: Frontend Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies
        run: |
          cd frontend
          npm ci
      - name: Run Programmatic Checks
        run: |
          cd frontend
          npm run lint
          npm run format
      - name: Ensure Working Tree Clean
        run: |
          if ! git diff --quiet -- frontend; then
            echo "Formatting or linting made changes. Please commit formatted files." >&2
            git status --short -- frontend
            exit 1
          fi
